language: python
python:
  - "2.7"
  - "3.4"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-numpy python-scipy

install:
  - pip install -r requirements.txt
  - python setup.py install

script: 
  - py.test

cache: apt
